version: '3'

services:
  spring-boot-rest-api-app:
    image: stage2_task5_docker_image
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      ["8087:8080"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/postgres
